# Site settings
title: LeapUNI
description: "Learn Engage Apply Perform"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Learn Engage Apply Perform
    hero_description: 今天进入未来，让我们帮助你成就更好的明天

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: 932 50 540
    emergency: 931 53 234
    email: info@leapuni.com
    address: Level 45 / 680 George St, <br> Sydney NSW 2000

# Opening hours
monday_friday: 9:00 – 18:00
saturday: 10:00 – 17:00
sunday: 10:00 – 15:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: 680 George St, Sydney NSW 2000, Australia
    address_details: svg/min/logo.svg

# Social settings
facebook: https://facebook.com
twitter: https://twitter.com
instagram: https://instagram.com
youtube: https://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2019 LeapUNI - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
